//! Integration tests for `polar.rs` — every edge case from todo.md §1.4.

mod common;

use common::*;
use orbswap_math::fixed_point::FIXED_SCALE;
use orbswap_math::polar::{cos_deg, get_delta_x, get_delta_y, sin_deg, PolarError};

// ---------------------------------------------------------------- paper vector

#[test]
fn paper_test_vector() {
    // L=10, y_in=6.07106781187, angle=135° → −0.875 (paper Appendix 3.3 / Desmos L14).
    let l = 10 * FIXED_SCALE;
    let y_in = f64_to_wad(6.07106781187);
    let got = get_delta_x(l, y_in, 135).unwrap();

    // Independent f64 oracle.
    let want =
        -10.0 * (1.0 - (6.07106781187f64 / 10.0).powi(2)).sqrt() - 10.0 * 135f64.to_radians().cos();
    assert_close(got, f64_to_wad(want), 100_000_000, "paper vector"); // 1e-10 vs oracle
                                                                      // And ≈ the documented −0.875 (the paper's value is display-rounded; the true
                                                                      // value is −0.87513478).
    assert_close(got, f64_to_wad(-0.875), 500_000_000_000_000, "≈ −0.875"); // 5e-4
}

// ---------------------------------------------------------------- tick boundary

#[test]
fn radicand_guard_returns_tick_boundary() {
    let l = 10 * FIXED_SCALE;
    // |y_in| > L → past the tick edge, not a NaN/panic.
    assert_eq!(
        get_delta_x(l, 11 * FIXED_SCALE, 45),
        Err(PolarError::TickBoundary)
    );
    assert_eq!(
        get_delta_x(l, -11 * FIXED_SCALE, 45),
        Err(PolarError::TickBoundary)
    );
    assert_eq!(
        get_delta_y(l, 11 * FIXED_SCALE, 45),
        Err(PolarError::TickBoundary)
    );
}

#[test]
fn boundary_at_exactly_l() {
    // y_in = L ⇒ radicand 0 ⇒ radial part 0 ⇒ Δx = −L·cos(angle).
    let l = 10 * FIXED_SCALE;
    let got = get_delta_x(l, l, 0).unwrap(); // cos 0 = 1 → −L
    assert_close(got, -l, 4, "Δx at y_in=L, angle 0");
    let got90 = get_delta_x(l, l, 90).unwrap(); // cos 90 ≈ 0 → ≈ 0
    assert_close(got90, 0, 1_000_000, "Δx at y_in=L, angle 90"); // f64 cos(90°)≈6e-14
}

#[test]
fn invalid_liquidity() {
    assert_eq!(get_delta_x(0, 0, 45), Err(PolarError::InvalidLiquidity));
    assert_eq!(get_delta_x(-5, 0, 45), Err(PolarError::InvalidLiquidity));
}

// ---------------------------------------------------------------- trig table

#[test]
fn cos_sin_table_known_angles() {
    // Tolerance 1e6 WAD (1e-12): near-zero angles carry f64's ~6e-14 trig error
    // (e.g. cos(90°) ≈ 6.1e-17, not exactly 0), which is negligible for the AMM.
    let s2 = f64_to_wad(2f64.sqrt() / 2.0); // √2/2
    let t = 1_000_000;
    assert_close(cos_deg(0), FIXED_SCALE, t, "cos 0");
    assert_close(sin_deg(0), 0, t, "sin 0");
    assert_close(cos_deg(45), s2, t, "cos 45");
    assert_close(sin_deg(45), s2, t, "sin 45");
    assert_close(cos_deg(90), 0, t, "cos 90");
    assert_close(sin_deg(90), FIXED_SCALE, t, "sin 90");
    assert_close(cos_deg(135), -s2, t, "cos 135");
    assert_close(sin_deg(135), s2, t, "sin 135");
    assert_close(cos_deg(180), -FIXED_SCALE, t, "cos 180");
}

#[test]
fn trig_table_vs_f64_all_degrees() {
    // Compare each table entry to f64 at the *normalized* degree (same computation
    // build.rs used) — so this validates the table generation exactly. Large raw
    // angles are covered by `angle_normalization_wraps`.
    for d in -720i128..=720 {
        let nd = d.rem_euclid(360);
        assert_close(
            cos_deg(d),
            f64_to_wad((nd as f64).to_radians().cos()),
            4,
            "cos",
        );
        assert_close(
            sin_deg(d),
            f64_to_wad((nd as f64).to_radians().sin()),
            4,
            "sin",
        );
    }
}

#[test]
fn angle_normalization_wraps() {
    assert_eq!(cos_deg(0), cos_deg(360));
    assert_eq!(cos_deg(45), cos_deg(45 + 720));
    assert_eq!(cos_deg(-45), cos_deg(315));
    assert_eq!(sin_deg(-90), sin_deg(270));
}

// ---------------------------------------------------------------- symmetry

#[test]
fn get_delta_y_mirrors_get_delta_x() {
    // Δy(l, v, θ) = −L√(…) − L·sin θ = −L√(…) − L·cos(90−θ) = Δx(l, v, 90−θ).
    let l = 10 * FIXED_SCALE;
    let mut rng = Rng::new(0xACE);
    for _ in 0..5_000 {
        let v = rng.range_i128(-l, l);
        let theta = rng.range_i128(-400, 400);
        let dy = get_delta_y(l, v, theta).unwrap();
        let dx = get_delta_x(l, v, 90 - theta).unwrap();
        // sin(θ) and cos(90−θ) are generated by independent f64 calls in build.rs,
        // so they can differ by ~1 ULP → ~1e3 WAD after ×L. Not bit-identical.
        assert_close(dy, dx, 1_000_000, "mirror v={v} θ={theta}");
    }
}

// ---------------------------------------------------------------- oracle sweep

#[test]
fn delta_x_matches_oracle_sweep() {
    let l = 1000 * FIXED_SCALE;
    let mut rng = Rng::new(77);
    for _ in 0..10_000 {
        let y_in = rng.range_i128(-l, l);
        let angle = rng.range_i128(0, 359);
        let got = get_delta_x(l, y_in, angle).unwrap();
        let lf = 1000.0;
        let yf = (y_in as f64) / 1e18;
        let want = -lf * (1.0 - (yf / lf).powi(2)).sqrt() - lf * (angle as f64).to_radians().cos();
        // WAD result vs f64 oracle: ~1e-9 relative on an L=1000 scale.
        assert!(
            ((got as f64) / 1e18 - want).abs() <= want.abs() * 1e-9 + 1e-6,
            "oracle: got {} want {want} (y_in={y_in} angle={angle})",
            (got as f64) / 1e18
        );
    }
}
