//! Generates the compile-time cos/sin lookup tables (WAD fixed-point) used by
//! `polar.rs`. Runs on the host (std/float available); the emitted file is a
//! plain `[i128; 360]` array, so the library stays `no_std` and float-free.

use std::{env, fs, path::Path};

fn main() {
    let out = env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let dest = Path::new(&out).join("trig_table.rs");
    let scale = 1e18_f64;

    let mut cos = String::from("/// cos(θ°)·1e18 for θ = 0..359 (generated by build.rs).\npub const COS_WAD: [i128; 360] = [");
    let mut sin = String::from("/// sin(θ°)·1e18 for θ = 0..359 (generated by build.rs).\npub const SIN_WAD: [i128; 360] = [");
    for d in 0..360 {
        // Match `f64::to_radians` (self * (PI/180)) exactly so tests can validate
        // the table against the stdlib conversion to the ULP.
        let rad = (d as f64).to_radians();
        cos.push_str(&format!("{},", (rad.cos() * scale).round() as i128));
        sin.push_str(&format!("{},", (rad.sin() * scale).round() as i128));
    }
    cos.push_str("];\n");
    sin.push_str("];\n");

    fs::write(&dest, format!("{cos}{sin}")).expect("write trig_table.rs");
    println!("cargo:rerun-if-changed=build.rs");
}
